// Generated by CoffeeScript 1.8.0
(function() {
  var RuleBook;

  RuleBook = (function() {
    function RuleBook() {
      this.rules = [];
      this.closed = false;
    }

    RuleBook.prototype.addRule = function(rule) {
      if (this.closed) {
        throw new Error('RuleBook is already closed, ' + 'you can\'t add rules anymore');
      }
      if (rule != null) {
        return this.rules.push(rule);
      }
    };

    RuleBook.prototype.close = function() {
      return this.closed = true;
    };

    RuleBook.prototype.getRules = function() {
      return this.rules;
    };

    return RuleBook;

  })();

  module.exports = RuleBook;

}).call(this);
